import logo from './images/logo.png'
import profile from './images/pp.jpg'
import pro1 from './proscreenshort/fashion_design.png'
import pro2 from './proscreenshort/kalabhuna.jpg'
import pro3 from './proscreenshort/sports_village.png'
import pro4 from './proscreenshort/work_opprotunity.png'
import pro5 from './proscreenshort/onlinestore.jpg'
import pro6 from './proscreenshort/exam.jpg'
import pro7 from './proscreenshort/news.jpg'
import pro8 from './proscreenshort/care-link.png'
export {logo, profile, pro1, pro2, pro3, pro4, pro5,pro6,pro7,pro8}